### ISSUE TITLE
Auspice crashes when sequence name contains characters that are not allowed in CSS selectors

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/auspice#1208]
**Current Behavior**  
Auspice crashes when sequence name contains characters that are not allowed in CSS selectors.

The following errors are shown in the console:
```
auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#tip_some<unsafehtmlcharacters:hereclades' is not a valid selector.
    at SVGSVGElement.<anonymous> (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1:84705)
    at J.select (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1:125075)
    at a.Ve (https://auspice.us/dist/auspice.chunk.6.bundle.ecd503d56f440eb012ff.js:1:53779)
    at SVGCircleElement.<anonymous> (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:2:61827)
    at SVGSVGElement.<anonymous> (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1:84705)
    at J.select (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1:125075)
    at a.Be (https://auspice.us/dist/auspice.chunk.6.bundle.ecd503d56f440eb012ff.js:1:51700)
    at SVGCircleElement.<anonymous> (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:2:61827)
(anonymous) @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1
select @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1
Ve @ auspice.chunk.6.bundle.ecd503d56f440eb012ff.js:1
(anonymous) @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:2
(anonymous) @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1
select @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1
Be @ auspice.chunk.6.bundle.ecd503d56f440eb012ff.js:1
(anonymous) @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:2
auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#tip_some<unsafehtmlcharacters:hereclades' is not a valid selector.
    at SVGSVGElement.<anonymous> (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1:84705)
    at J.select (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1:125075)
    at a.Be (https://auspice.us/dist/auspice.chunk.6.bundle.ecd503d56f440eb012ff.js:1:51700)
    at SVGCircleElement.<anonymous> (https://auspice.us/dist/auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:2:61827)
(anonymous) @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1
select @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:1
Be @ auspice.chunk.6.bundle.ecd503d56f440eb012ff.js:1
(anonymous) @ auspice.chunk.other-vendors.bundle.7bee8f549fbad873d554.js:2


```

**Expected behavior**  
Auspice never crashes.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Have a tree JSON with a sequence named `some<unsafe|html/characters:here`  
2. Drop this JSON onto auspice.us
3. Mousehover the node corresponding to this sequence 
4. Check dev console for errors
5. Note that the application no longer responds

**Possible solution**  
Sanitize all instances of runtime-generated CSS selectors and HTML entries containing user input, for example using [CSS.escape](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape) (possibly with [pollyfil](https://github.com/mathiasbynens/CSS.escape) for IE support)

**Your environment: if browsing Nextstrain online**  
 - Operating system: N/A  
 - Browser: Chromium 83, Firefox 80

**Additional context**

**Comment by ivan-aksamentov** [comment]
It is probably safe to say that this particular issue is fixed in #1209. And if there are more problems that we can open more issues.
