### ISSUE TITLE
Unexpected redux state mutations

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1742]
### Current Behavior

Certain actions will trigger a `Error: Invariant failed: A state mutation was detected between dispatches` error. These errors only appear in development mode. 

Behaviour observed on 19f5c2cafbb2d0276ad9d26511d146f5befb7183 (part of the master branch).

I can somewhat reliably generate this via:
* Adding a number of filters. Example error details: `in the path 'controls.filters.country.0'.` 
* Loading a narrative which defines multiple datasets. Example error details: `in the path: jsonCache.jsons.zika-inline.`, `'jsonCache.jsons.zika.pathname'`. (My guess would be this is the promises resolving; haven't investigated.) This causes the app to crash (only when in dev mode).

**Comment by joverlee521** [comment]
I also ran into this error when loading a narrative with multiple datasets in dev mode. 
I'm currently working around it with
```
SKIP_REDUX_CHECKS=true npm run dev
```

**Comment by jameshadfield** [comment]
Consistent with the above, nextstrain/auspice.us development will also fail for narratives without `SKIP_REDUX_CHECKS=true`:

```
immutableStateInvariantMiddleware.ts:96 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at new Set (<anonymous>)
    at trackProperties (immutableStateInvariantMiddleware.ts:96:3)
    at trackProperties (immutableStateInvariantMiddleware.ts:110:31)
    <etc>
```
