### ISSUE TITLE
Getting following crash/whiteout, probably since Auspice 2.60.0: `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1895]
### Current Behavior
I've hit the following whiteout crash of Auspice multiple times today - I don't remember ever seeing a whiteout like this (at least not in the past few months) so this must be due to a recent change in a recent release.

I've also hit it on Nextclade master: https://github.com/nextstrain/nextclade/issues/1547 which uses  2.60.0 as well.

I hit it multiple times not thinking anything, just reloading the page. Only after filing the Nextclade issue did I look at the console and realized that this is probably an Auspice bug, not a Nextclade bug.

```
17:11:23.630 auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at B (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:2310)
    at Y._setSelectedNodes (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:7380)
    at Y.update (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:5079)
    at l.value (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:37588)
    at Ei (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:65453)
    at Ua (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:83928)
    at Es (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:120612)
    at Tu (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:112074)
    at Su (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:111999)
    at vu (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:109025)
```

We might want to revert to 2.59.1 unless we have a quick fix for this as it has come up independently around 5 times or more already today. I've added priority: high for now.

Unfortunately I don't know how to reproduce it (yet). Example tree where I encountered this: https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice11_genome_test_55b41_3699e0.json?c=gt-nuc_2091&gmax=17887&gmin=15887&gt=nuc.1674C&label=id:node_7178235 - but not limited to this tree, I've encountered it on a variety of trees.

Tree JSON: 
[fetch_genome-test.gi.ucsc.edu_trash_hgPhyloPlace_subtreeAuspice11_genome_test_55b41_3699e0.json.json](https://github.com/user-attachments/files/17719561/fetch_genome-test.gi.ucsc.edu_trash_hgPhyloPlace_subtreeAuspice11_genome_test_55b41_3699e0.json.json)

Error points at `_setSelectedNodes` being involved which is in this file: https://github.com/nextstrain/auspice/blob/e8337a8ef1beb372e942fdfce5823d131c957263/src/components/entropy/entropyD3.js#L191 which was also recently changed. So might be related to some of @jameshadfield's recent perf improvements.

<details>

```log
17:11:23.630 auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at B (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:2310)
    at Y._setSelectedNodes (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:7380)
    at Y.update (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:5079)
    at l.value (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:37588)
    at Ei (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:65453)
    at Ua (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:83928)
    at Es (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:120612)
    at Tu (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:112074)
    at Su (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:111999)
    at vu (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:109025)
as @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
n.callback @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
gi @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
fs @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Cu @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
t.unstable_runWithPriority @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
$o @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Ou @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
vu @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
(anonymous) @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
t.unstable_runWithPriority @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
$o @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Qo @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Xo @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
mu @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
notify @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
notifyNestedSubs @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
o @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
g @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
dispatch @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
dispatch @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
value @ auspice.chunk.928.bundle.41a3efacc6aed0cf56e5.js:2
(anonymous) @ auspice.chunk.928.bundle.41a3efacc6aed0cf56e5.js:2
v @ auspice.chunk.other-vendors.bundle.160c684012f52edf64fc.js:2
x @ auspice.chunk.other-vendors.bundle.160c684012f52edf64fc.js:2
w @ auspice.chunk.other-vendors.bundle.160c684012f52edf64fc.js:2
17:11:23.631 auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at B (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:2310)
    at Y._setSelectedNodes (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:7380)
    at Y.update (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:5079)
    at l.value (auspice.chunk.387.bundle.9cd3699284d72342714a.js:1:37588)
    at Ei (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:65453)
    at Ua (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:83928)
    at Es (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:120612)
    at Tu (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:112074)
    at Su (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:111999)
    at vu (auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2:109025)
B @ auspice.chunk.387.bundle.9cd3699284d72342714a.js:1
Y._setSelectedNodes @ auspice.chunk.387.bundle.9cd3699284d72342714a.js:1
Y.update @ auspice.chunk.387.bundle.9cd3699284d72342714a.js:1
value @ auspice.chunk.387.bundle.9cd3699284d72342714a.js:1
Ei @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Ua @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Es @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Tu @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Su @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
vu @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
(anonymous) @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
t.unstable_runWithPriority @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
$o @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Qo @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
Xo @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
mu @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
notify @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
notifyNestedSubs @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
o @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
g @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
dispatch @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
dispatch @ auspice.core-vendors.bundle.4653d4d814c0c7bfd800.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
(anonymous) @ auspice.chunk.251.bundle.fd436d89122437304aeb.js:2
value @ auspice.chunk.928.bundle.41a3efacc6aed0cf56e5.js:2
(anonymous) @ auspice.chunk.928.bundle.41a3efacc6aed0cf56e5.js:2
v @ auspice.chunk.other-vendors.bundle.160c684012f52edf64fc.js:2
x @ auspice.chunk.other-vendors.bundle.160c684012f52edf64fc.js:2
w @ auspice.chunk.other-vendors.bundle.160c684012f52edf64fc.js:2
```

</details>

**Comment by corneliusroemer** [comment]
> Alright, got a repro:
@ivan-aksamentov you genius! I've noticed the entropy panel has become a bit sluggish recently, maybe that's related to the bug and perf improvements

Cool, I just needed to add both goals and properties, they were autoshown when I clicked on the dropdown. So really easy to setup, nice! Should definitely be possible to do for Auspice as well, will also suggest this to Loculus, thanks! https://plausible.io/master.clades.nextstrain.org/settings/properties
